### ISSUE TITLE
Did this stop working today?

### ISSUE THREAD

**Issue by dpjanes** [JkeFos/hide-twitter-trending#13]
Was working great, this morning everything started showing up again

**Comment by ppeau** [comment]
yep stop working

**Comment by nuenuewei** [comment]
Manually blocking the elements with ublock origin also quit working in waterfox(twitter.com##[aria-label="Timeline: Trending now"]) so whatever changed is bigger than this extension.

Man, they're really desperate to push that propaganda

**Comment by JkeFos** [comment]
Hey guys, I just noticed this. I will try to fix it ASAP.

**Comment by JkeFos** [comment]
I have submitted a fix to the extension stores. It normally takes a few days of processing until the update is published. 
Sorry for the inconvenience.

**Comment by Spongeboblover** [comment]
I had mine for a month and it just stopped working today please fix it?

**Comment by JkeFos** [comment]
@Spongeboblover I have submitted a update to the extension stores that will fix the problem. So far, only Firefox has published the update whilst Chrome and Edge are still processing. Processing normally takes around 2 days.

**Comment by JkeFos** [comment]
Unfortunately, Google has blocked my extension from being updated for vague reasons.

I have found an alternate extension to remove twitter trends, please use this one: https://chrome.google.com/webstore/detail/calm-twitter/cknklikacoaeledfaldmhabmldkldocj
