### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by Rajput245** [JkeFos/hide-twitter-trending#16]
hi thanks for your valuable work. i was able to keep myself stay away from political garbage.it was working fine till yesterday but its not working today please help us as this was the only possible solution that i could find to stop those stupid and hate-full trends.
i just use twitter for just educational purpose.

**Comment by JkeFos** [comment]
Hello, Twitter made some changes to their site but I have submitted a update to fix this. I expect the store to publish it in a couple of days. 

Please follow issue #13 for updates.

Sorry for the inconvenience!
