### ISSUE TITLE
All media is now being blocked

### ISSUE THREAD

**Issue by TotemSP2** [JkeFos/hide-twitter-trending#17]
No media is shown while the extension is active.

### Before
![chrome_2020-07-10_15-49-34](https://user-images.githubusercontent.com/16230991/87121117-6e1d9600-c2c5-11ea-8692-4d1b6121301c.png)

### After
![chrome_2020-07-10_15-49-09](https://user-images.githubusercontent.com/16230991/87121138-770e6780-c2c5-11ea-9074-340e1d474895.png)

Additionally, my only recourse while this is being fixed, is to use **Giant** Twitter (by zooming it in by 200% on 1080p resolutions) This is fine, for the time being.

![chrome_2020-07-10_15-54-42](https://user-images.githubusercontent.com/16230991/87121238-b046d780-c2c5-11ea-8c49-f6b57bd47f44.png)

**Comment by JkeFos** [comment]
Thanks for letting me know. Someone else has notified me this was a unintended consequence of the last update to fix #13. I have already pushed another update to the store which fixes this. Should be published in 1-2 days.

Very sorry for the inconvenience.

**Comment by Spongeboblover** [comment]
Thank you for fixing it the first time but now I can't see any pictures. Please fix that?

**Comment by JkeFos** [comment]
Unfortunately, Google has blocked my extension from being updated for vague reasons. 

I have found an alternate extension to remove twitter trends, please use this one: https://chrome.google.com/webstore/detail/calm-twitter/cknklikacoaeledfaldmhabmldkldocj

**Comment by TotemSP2** [comment]
That's a shame, I hope you can get something worked out, but I'll check that extension out in the meantime.

**Comment by Golfhaus** [comment]
Your extension has been a lifesaver, sir. Or at least a sanity saver. Thanks for the efforts.

**Comment by Spongeboblover** [comment]
Thank you
