### ISSUE TITLE
Still not working as expected

### ISSUE THREAD

**Issue by ppeau** [JkeFos/hide-twitter-trending#19]
It is weird that nobody notice that but for me, on chrome if I activate the new version of your extension everything except text is blocked. not only on right part but all photos, videos, post links except text have been removed from all posts which is quite brutal :-)
Before and after

![ext](https://user-images.githubusercontent.com/357328/87858677-a2183d00-c8fd-11ea-8f0e-fd07301534ab.png)

**Comment by JkeFos** [comment]
Hi Pat, I'm aware of this issue but unfortunately Google is not allowing me to push updates to the extension for vague reasons. 
I have been using this alternative extension instead: https://chrome.google.com/webstore/detail/calm-twitter/cknklikacoaeledfaldmhabmldkldocj
