### ISSUE TITLE
Hiding all images

### ISSUE THREAD

**Issue by WraithTDK** [JkeFos/hide-twitter-trending#20]
The extension appears to be hiding all pictures that my friends are tweeting out, not just the things in the trending box.

**Comment by JkeFos** [comment]
Thanks for letting me know but unfortunately Google has blocked my extension from being updated for vague reasons.

I have found an alternate extension to remove twitter trends, please use this one: https://chrome.google.com/webstore/detail/calm-twitter/cknklikacoaeledfaldmhabmldkldocj

**Comment by WraithTDK** [comment]
Well THAT sucks. Your extension was awesome. Well, I guess I'll take your
advice and switch to calm. Just wanted to say thank you for the work you
did. Things are so ugly right now. people are so angry and Twitter is just
so over-flowing with people raging about everyone and everything, I've
become quite overwhelmed by the level of negativity...and yet with
quarantine in place, it's very difficult to feel any sort of connection to
other human beings without social media. Being able to filter out the
trending noise is a HUGE help.
