### ISSUE TITLE
Doesn't work with non-default background

### ISSUE THREAD

**Issue by robot-dreams** [JkeFos/hide-twitter-trending#4]
Great extension, exactly what I was looking for!

At first I thought it didn't work, but then I realized I had to set the background to "default" for the extension to work (I previously had it set to "dim").

### Background settings

<img width="1047" alt="Background Setting" src="https://user-images.githubusercontent.com/4276679/78534916-1b9d7c80-77a0-11ea-8b9d-dc1c2556e0a9.png">

### Works with "default"

<img width="506" alt="Works with Default" src="https://user-images.githubusercontent.com/4276679/78534977-353ec400-77a0-11ea-9020-0b8e1b8c775b.png">

### Doesn't work with "dim"

<img width="538" alt="Dim" src="https://user-images.githubusercontent.com/4276679/78534998-3f60c280-77a0-11ea-8340-603a6774fe30.png">

**Comment by JkeFos** [comment]
Thanks for letting me know about this, I'll fix it soon.

**Comment by JkeFos** [comment]
I have updated the code on GitHub so that all backgrounds are now supported. I'm having problems pushing the update to the Chrome Web Store due to global conditions but hopefully Google will respond soon!

**Comment by robot-dreams** [comment]
Thanks for the fix!

**Comment by JkeFos** [comment]
The extension has just been updated on the Chrome Web Store, FYI.

**Comment by robot-dreams** [comment]
Confirmed that it works for me on "Dim" and "Lights Out" now, thanks again!
